export enum ActivityType {
  SIGHTSEEING = 'SIGHTSEEING',
  NATURE_AND_OUTDOORS = 'NATURE_AND_OUTDOORS',
  CULTURAL_EXPERIENCE = 'CULTURAL_EXPERIENCE',
  FOOD_AND_DINING = 'FOOD_AND_DINING',
  ENTERTAINMENT = 'ENTERTAINMENT',
  OTHER = 'OTHER',
}
